FROM golang:alpine

ARG GITHUB_BRANCH

RUN apk update && apk add git
RUN go get -u github.com/FiloSottile/gvt

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/adcp-control-microservice

WORKDIR /go/src/github.com/byuoitav/adcp-control-microservice
RUN gvt fetch -branch ${GITHUB_BRANCH} github.com/byuoitav/configuration-database-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/adcp-control-microservice"]

EXPOSE 8012
